// <auto-generated />
namespace AnotherShopping.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FirstMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201410212107155_FirstMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
